let grid = d3.select('#grid')
let charts = ["Area stacked", "Area stacked small multiple", "Bar chart Split", "Bar chart horizontal", "Bar chart horizontal with dropdrown", "Bar chart horizontal small multiple", "Bar chart horizontal with reference small multiple", "Bar chart horizontal small multiple with colour", "Bar chart horizontal clustered", "Bar chart horizontal stacked", "Bar chart horizontal stacked with tooltip", "Bar chart horizontal stacked sm", "Bar chart horizontal stacked grouped", "Bar chart horizontal stacked clustered", "Bar chart horizontal grouped", "Bar chart horizontal grouped clustered", "Bar chart horizontal stacked clustered grouped", "Bubble plot animated", "Comet plot", "Column chart", "Column chart small multiple", "Column chart stacked", "Column chart stacked with line", "Column chart stacked sm", "Dot plot", "Dot plot with confidence intervals sm", "Heatmap", "Heatmap by column", "Line chart", "Line chart with dropdown", "Line chart small multiple", "A line chart with area shading", "Population pyramid", "Population pyramid with comparison toggle", "Population pyramid with a static comparison", "Population pyramid with dropdown", "Population pyramid with dropdown and interactive comparison", "Range plot", "Scatter plot", "Scatter plot small multiple", "Scatter plot animated"];
let urls = ["https://onsvisual.github.io/Charts/area-stacked/", "https://onsvisual.github.io/Charts/area-stacked-sm/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-split/", "https://onsvisual.github.io/Charts/bar-chart-horizontal/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-with-dropdown/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-sm/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-with-reference-sm/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-sm-colour/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-clustered/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-stacked/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-stacked-with-tooltip/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-stacked-sm/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-stacked-grouped/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-stacked-clustered/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-grouped/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-grouped-clustered/", "https://onsvisual.github.io/Charts/bar-chart-horizontal-stacked-clustered-grouped/", "https://onsvisual.github.io/Charts/bubble-chart-animated/", "https://onsvisual.github.io/Charts/comet-plot/", "https://onsvisual.github.io/Charts/column-chart/", "https://onsvisual.github.io/Charts/column-chart-sm/", "https://onsvisual.github.io/Charts/column-chart-stacked/", "https://onsvisual.github.io/Charts/column-chart-stacked-with-line/", "https://onsvisual.github.io/Charts/column-chart-stacked-sm/", "https://onsvisual.github.io/Charts/dot-plot/", "https://onsvisual.github.io/Charts/dot-plot-with-ci-sm/", "https://onsvisual.github.io/Charts/heatmap/", "https://onsvisual.github.io/Charts/heatmap-per-column/", "https://onsvisual.github.io/Charts/line-chart/", "https://onsvisual.github.io/Charts/area-stacked/", "https://onsvisual.github.io/Charts/line-chart-sm/", "https://onsvisual.github.io/Charts/line-chart-with-area/", "https://onsvisual.github.io/Charts/population-pyramid-static/", "https://onsvisual.github.io/Charts/population-pyramid-with-comparison-toggle/", "https://onsvisual.github.io/Charts/population-pyramid-static-with-comparison/", "https://onsvisual.github.io/Charts/population-pyramid-with-dropdown/", "https://onsvisual.github.io/Charts/population-pyramid-with-dropdown-and-interactive-comparison/", "https://onsvisual.github.io/Charts/range-plot/", "https://onsvisual.github.io/Charts/scatter-plot/", "https://onsvisual.github.io/Charts/scatter-plot-sm/", "https://onsvisual.github.io/Charts/scatter-plot-animated/"];
let url = "https://onsvisual.github.io/Charts/";

for (let i = 0; i < charts.length; i++) {
	grid.append('div').attr('id', 'container' + i).attr('class', 'container')
	d3.select('#container' + i).append('div').attr('id', 'title' + i).attr('class', 'title-div').text(charts[i])
	d3.select('#container' + i).append('button').attr('type', 'button').attr('id', 'btn' + i).attr('class', 'reveal')

	d3.select('#container' + i).append('div').attr('id', 'chart' + i).attr('class', 'chart')
	d3.select('#container' + i).append('div').attr('id', 'data' + i).html(`<a href=${urls[i]}data.csv download>Download the data csv file</a>`)

	d3.select('#container' + i).append('div').attr('id', 'modal' + i).attr('class', 'modal modal-content').html(`    <span class="close">&times;</span>
    <p>Some text in the Modal..</p>`)

	let modal = d3.select('#modal' + i)
	let btn = d3.select('#btn' + i)
	let span = d3.selectAll('.close')

	let pymParent = new pym.Parent(`chart${i}`, `${urls[i]}`, {})


}